defaults:
  - base
  - _self_

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - gsm8k_train
test_dataset_names:
  - gsm8k_test

model_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main

vllm_config:
  vllm_kwargs:
    max-model-len: ${finetune.seq_length}

world:
  replicas: 1
  actor_fraction: 4
  preprocessor_fraction: 0
  finetune_fraction: 4
  env_replicas: 2
  actor_group_port: 9000
  environment_start_port: 7777
