defaults:
    - base
    - _self_


# For debugging to skip test set rollouts
eval_every_n_versions: 0

finetune:
  train_batch_size: 1
  valid_batch_size: 1
  gradient_accumulation_passes: 4
  seq_length: 2048
  seq_parallel: 1
  attempts: 2
  max_train_steps: 100
  save_checkpoint_steps: 5
  push_to_hub: true
  hub_model_id: hf-imo-colab/test-push
  hub_model_revision: v00.00
  hub_ignore_patterns:
    - "*.mp4"
    - "*.png"

llm:
  parameters:
    max_tokens: 32 
    temperature: 1.0

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - open_reasoner_zero_57k
test_dataset_names:
  - aime_2024
model_path: Qwen/Qwen2.5-0.5B-Instruct

vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${actor.llm_max_rollouts}
    max-num-batched-tokens: 1024
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    tensor-parallel-size: 1
    pipeline-parallel-size: 1
    generation-config: vllm

world:
  replicas: 1
  actor_fraction: 4
  preprocessor_fraction: 0
  finetune_fraction: 4
  env_replicas: 2
  actor_group_port: 9000
  environment_start_port: 7777
