defaults:
    - base
    - _self_

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
llm:
  parameters:
    chat_template_kwargs:
      enable_thinking: false
test_llm:
  parameters:
    chat_template_kwargs:
      enable_thinking: false
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - pope_hard_with_guide
test_dataset_names:
  - pope_hard_no_guide_test
  - aime_2025