# --------------------
# Config for 4+3 nodes
# --------------------
defaults:
    - base
    - _self_

model_path: Qwen/Qwen3-4B-Thinking-2507
# Eval every 45 steps (each batch is 32 samples with grad accumulation of 24 -> 768 updates per eval)
eval_every_n_versions: 34560

preprocess:
  shared_memory_entry_size: 2000000000

finetune:
  attempts: 16
  train_batch_size: 32
  valid_batch_size: 32
  gradient_accumulation_passes: 24
  seq_length: 49920
  seq_parallel: 2
  learning_rate: 1.0e-6
  save_checkpoint_steps: 10
  push_to_hub: true
  hub_model_id: hf-imo-colab/Qwen3-4B-Thinking-2507-Proof
  hub_model_revision: v01.00
  hub_ignore_patterns:
    - "*.pt"
    - "*.pth"

llm:
  parameters:
    max_tokens: 49152 
    temperature: 0.8
# Sampling params taken from Qwen3 tech report: https://arxiv.org/abs/2505.09388
test_llm:
  parameters: 
    max_tokens: 49152
    temperature: 0.8 
    top_p: 0.95
    top_k: 20

llm_grader:
  name: openai/gpt-oss-20b # or gpt-oss-120b-twj if running via inference endpoints
  vllm_kwargs:
    num_nodes: 2
    data-parallel-size: 16
    tensor-parallel-size: 1
    max-num-batched-tokens: 8192
    max-num-seqs: 32
    max-model-len: 81920
    gpu-memory-utilization: 0.9
  sampling_kwargs:
    temperature: 1.0
    max_output_tokens: 65536
    reasoning:
      effort: medium
  reasoning_delimiters: ["</think>"]

actor:
  llm_max_rollouts: 32
  shared_memory_entry_size: 2000000000 # Allow up to 2GB per rollout
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathProofEnvironment
  model_name: ${llm_grader.name}
  sampling_kwargs: ${llm_grader.sampling_kwargs}
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - hub_id: hf-imo-colab/olympiads-proof-schema
    split: train
test_dataset_names:
  - hub_id: hf-imo-colab/olympiads-proof-schema-benchmark
    split: IMO2025

vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: 24 # Larger values exhaust the KV cache
    max-num-batched-tokens: 32768
    max-model-len: ${finetune.seq_length}
    enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    tensor-parallel-size: 1
    pipeline-parallel-size: 1
    generation-config: vllm

world:
  replicas: 1
  actor_fraction: 32
  preprocessor_fraction: 0
  finetune_fraction: 24
  env_replicas: 1
  actor_group_port: 9000
  environment_start_port: 7777
