# --------------------
# Config for 2+1 nodes
# --------------------
defaults:
    - base
    - _self_

model_path: Qwen/Qwen3-4B-Thinking-2507
# Uncomment to skip test set rollouts
eval_every_n_versions: 0

finetune:
  attempts: 16
  train_batch_size: 32
  valid_batch_size: 32
  gradient_accumulation_passes: 16
  seq_length: 49920
  seq_parallel: 2
  learning_rate: 1.0e-6
  save_checkpoint_steps: 50
  push_to_hub: true
  hub_model_id: hf-imo-colab/Qwen3-4B-Thinking-2507-Proof
  hub_model_revision: v00.03
  hub_ignore_patterns:
    - "*.pt"
    - "*.pth"

llm:
  parameters:
    max_tokens: 49152 
    temperature: 0.8
# Sampling params taken from Qwen3 tech report: https://arxiv.org/abs/2505.09388
test_llm:
  parameters: 
    max_tokens: 49152
    temperature: 0.8 
    top_p: 0.95
    top_k: 20

llm_grader:
  name: openai/gpt-oss-20b # or gpt-oss-120b-twj if running via inference endpoints
  num_nodes: 2
  dp: 16
  tp: 1
  sampling_kwargs:
    temperature: 1.0
    max_output_tokens: 49152
    reasoning:
      effort: medium
  reasoning_delimiters: ["</think>"]

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathProofEnvironment
  model_name: ${llm_grader.name}
  sampling_kwargs: ${llm_grader.sampling_kwargs}
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - hub_id: hf-imo-colab/olympiads-proof-schema
    split: train
test_dataset_names:
  - hub_id: hf-imo-colab/olympiads-proof-schema-benchmark
    split: IMO2025

vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${actor.llm_max_rollouts}
    max-num-batched-tokens: 1024
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    tensor-parallel-size: 1
    pipeline-parallel-size: 1
    generation-config: vllm

world:
  replicas: 1
  actor_fraction: 16
  preprocessor_fraction: 0
  finetune_fraction: 8
  env_replicas: 1
  actor_group_port: 9000
  environment_start_port: 7777
