defaults:
  - streams: files
  - rewards: pure_success
  - _self_

seed: 42

# Main model path for RC actor and regular actor
model_path: ars22/rc_qwen3_4b_thinking_2507_proof-20260112-064952
model_revision: null

# Separate model for summarization (optional)
# If not set or null, uses the same model as RC actor
summarization_model_path: Qwen/Qwen3-4B-Instruct-2507
summarization_model_revision: main


# evaluation settings
eval_only: true # set to true to only evaluate the model with RC actor
skip_first_eval: true
eval_every_n_versions: 12800

# world configuration for a 4 node (32 H100 GPU) setup
world:
  replicas: 1
  # GPU allocation fractions (must sum to <= 8 per node)
  rc_actor_fraction: 28  # GPUs for RC actor LLMs
  summarization_fraction: 4  # Set to >0 to use separate summarization LLMs
  finetune_fraction: 0
  actor_fraction: 0    # GPUs for regular actor LLMs
  preprocessor_fraction: 0

  env_replicas: 2

  actor_group_port: 9000
  environment_start_port: 7777

# RC Actor configuration
rc_actor:
  log_each_n_secs: 0
  problem_queue_size: 20
  result_queue_size: ${rc_actor.problem_queue_size} 
  llm_max_rollouts: 20  
  summarization_max_rollouts: 140 # llm_max_rollouts * world.rc_actor_fraction / world.summarization_fraction 
  rollout_workers: 1
  discount_factor: 1
  throughput_window_size: 50
  shared_memory_entry_size: 2000000000 # Allow up to 2GB per rollout
  # Retry settings for transient HTTP errors (connection resets, etc.)
  max_retries: 10
  retry_base_delay: 1.0
  
  # RC-specific configuration
  num_reasoning_steps: 12  # Number of reasoning/summarization cycles
  attempts: 1  # Number of attempts per problem (for training use 1)

  # Solution and summarization rollout policies
  solution_rollout_policy: pipelinerl.domains.math.rollouts.generate_math_rollout_rc
  summarization_rollout_policy: pipelinerl.domains.math.rollouts.generate_summarization_rollout

  # Prompt template files (loaded from files)
  system_prompt: null
  reasoning_prompt_file: prompts/sum_e2e_complete_reasoning_prompt.txt
  summarization_prompt_file: prompts/sum_e2e_complete_summarization_prompt.txt
  
  # Task template for formatting the problem
  task_template: |-
    {task}
  
  # RC specific Model configuration
  use_think_tags: false
  model_class: "qwen"  # Options: "qwen", "gptoss", etc.
  reasoning_prompt_style: "structured"  # Options: "structured", "completion"
  summarization_style: "summ"  # Options: "summ", "sequential"



# LLM parameters for RC actor (solution generation)
llm:
  parameters: 
    max_tokens: 49152
    temperature: 0.8
    top_p: 0.95
    top_k: 20

test_llm:
  parameters: 
    max_tokens: 49152
    temperature: 0.8
    top_p: 0.95
    top_k: 20

# LLM parameters for summarization (optional)
# If not set, uses the same parameters as solution generation
summarization_llm:
  parameters:
    max_tokens: 2048
    temperature: 0.7
    top_p: 0.8
    top_k: 20

# vLLM configuration for RC actor LLMs
rc_actor_vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${rc_actor.llm_max_rollouts}
    max-num-batched-tokens: 16384
    max-model-len: 53000
    no-enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    generation-config: vllm
    tensor-parallel-size: 1

# vLLM configuration for summarization LLMs 
summarization_vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${rc_actor.summarization_max_rollouts}
    max-num-batched-tokens: 16384
    max-model-len: 53000
    no-enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    generation-config: vllm
    tensor-parallel-size: 1


# vLLM configuration for generation/actor LLMs
vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${rc_actor.llm_max_rollouts}
    max-num-batched-tokens: 16384
    max-model-len: 53000
    no-enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    generation-config: vllm
    tensor-parallel-size: 1
    pipeline-parallel-size: 1

    
# this will be autocreated based on the config
jobs: []



output_dir: ???
force_restart: false
pop_old_data: true
max_lag: null
attempts: ${rc_actor.attempts}
train_subset: null

# Dataset configuration
dataset_loader: pipelinerl.domains.math.load_datasets
dataset_loader_params:
  seed: 42
train_dataset_names:
  - imo_proof_bench
test_dataset_names:
  - imo_proof_bench
debug:
  mode: ""
  streams_from: null
  place_inference_workers: true
  use_existing_llms: false

me:
  # This will be autopopulated
  job_idx: null

hydra:
  run:
    dir: ${output_dir}

wandb:
  use_wandb: true
  wandb_id: null
  wandb_name: null
  # W&B entity name
  wandb_entity_name: null
  # W&B project name
  wandb_project_name: pipeline-rl
  # W&B resume policy
  wandb_resume: always
  # Whether to use only the basename or the full path as the run name
  wandb_use_basename: True
  wandb_workspace_root: null
  # set the group in your config
  wandb_group: null
  wandb_dir: null
  # Comma-separated list of keywords to tag the run.
  tags: []
  # Whether to log the verifier table to W&B, setting it to false to prevent wandb local directory growth
  log_verifier_table: true

environment:
  _target_: pipelinerl.domains.math.MathProofEnvironment
  model_name: ${llm_grader.name}
  sampling_kwargs: ${llm_grader.sampling_kwargs}
  prompt_name: ${llm_grader.prompt_name}
  
llm_grader:
  local: false # set to false to run via inference endpoints
  name: openai/gpt-oss-20b # or gpt-oss-120b-twj if running via inference endpoints
  vllm_kwargs:
    num_nodes: 1
    data-parallel-size: 8
    tensor-parallel-size: 1
    max-num-batched-tokens: 24576
    max-num-seqs: 64
    max-model-len: 98304
    gpu-memory-utilization: 0.9
  sampling_kwargs:
    temperature: 1.0
    max_output_tokens: 81920
    reasoning:
      effort: medium
  reasoning_delimiters: ["</think>"]
  prompt_name: v1
  wandb_table:
    enabled: true
    keep_last_k_groups: 32
    log_every_n_groups: 32