# Test configuration for RC Actor
# Minimal config for testing online reasoning/summarization rollouts
# Usage: python test_rc_actor.py --config-name test_rc

# Inherit from base
defaults:
  - base
  - _self_

# Model - use small model for fast testing
model_path: Qwen/Qwen3-4B-Instruct-2507

# Optional: Use a different (smaller/faster) model for summarization
# Uncomment to enable separate summarization model
summarization_model_path: Qwen/Qwen3-4B-Instruct-2507

# Random seed
seed: 42

# Output directory for test runs
output_dir: ./runs/test_rc

# vLLM configuration for generation/actor LLMs
vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.95
    num-scheduler-steps: 16
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: 256
    max-num-batched-tokens: 256000
    no-enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    generation-config: vllm
    tensor-parallel-size: 1
    max-model-len: 131072  # Set explicit context limit (128K tokens)

# vLLM configuration for summarization LLMs 
summarization_vllm_config:
  use_v1: false
  vllm_kwargs:
    enforce-eager: ""  # for summarization LLMs, to avoid TMA issues when trying to set aside GPU memory for CUDA optimizations.
    dtype: bfloat16
    gpu-memory-utilization: 0.90
    num-scheduler-steps: 16
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: 256
    max-num-batched-tokens: 256000  
    no-enable-prefix-caching: ""
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    generation-config: vllm
    tensor-parallel-size: 1
    max-model-len: 131072  # Set explicit context limit (128K tokens)

# Test world configuration (simplified version of world config)
# Controls GPU allocation for different LLM types
test_world:
  actor_fraction: 7  # Number of LLMs for actor/generation LLMs
  summarization_fraction: 1  # Number of LLMs for summarization LLMs (0 = use same LLMs as actor)
  env_replicas: 2
  environment_start_port: 7777
  actor_group_port: 9000

# RC Actor configuration
actor:
  # Number of reasoning/summarization cycles per problem
  num_reasoning_steps: 16
  
  # Rollout policies
  solution_rollout_policy: pipelinerl.domains.math.rollouts.generate_math_rollout
  summarization_rollout_policy: pipelinerl.domains.math.rollouts.generate_summarization_rollout
  system_prompt: Please reason step by step, and put your final answer within \boxed{}.
  
  # Prompt template files (loaded from files)
  reasoning_prompt_file: prompts/rc_reasoning_prompt.txt
  summarization_prompt_file: prompts/rc_summarization_prompt.txt
  
  # Task template for formatting the problem
  task_template: |-
    {task}
  
  # Rollout configuration
  rollout_workers: 1
  problem_queue_size: 128
  result_queue_size: 128
  shared_memory_entry_size: 15728640  # 15MB
  throughput_window_size: 10
  
  # Retry configuration
  max_retries: 3
  retry_base_delay: 1.0

# LLM generation parameters for reasoning/solution generation
llm:
  parameters:
    temperature: 0.7  
    max_tokens: 16384  # Longer reasoning chains
    top_p: 0.8
    top_k: 20

# LLM generation parameters for summarization 
summarization_llm:
  parameters:
    temperature: 0.7  
    max_tokens: 2048  # Shorter summaries
    top_p: 0.8
    top_k: 20

test_llm:
  parameters:
    temperature: 0.7
    max_tokens: 16384
    top_p: 0.8
    top_k: 20

# Streams backend
streams:
  backend: files

# Disable WandB for testing
wandb:
  use_wandb: false

# Training attempts (for online RC, we use 1 for training and higher values for evaluation)
attempts: 4

# Disable eval during test
eval_every_n_versions: 0

# Eval only mode
eval_only: true

# Debug mode
debug:
  mode: true

# Finetune config (minimal for state management)
finetune:
  max_lag: null


# Dataset configuration - using POPE hard dataset
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - imo_answer_bench
test_dataset_names:
  - imo_answer_bench

# Environment configuration 
environment:
  _target_: pipelinerl.domains.math.MathEnvironment

# LLM Grader configuration
llm_grader:
  name: openai/gpt-oss-20b
  vllm_kwargs:
    num_nodes: 2                    # number of nodes for the grader server
    data-parallel-size: 16          # data parallelism
    tensor-parallel-size: 1         # tensor parallelism
    max-num-batched-tokens: 8192    # tokenizer budget per batch
    max-num-seqs: 16                # concurrent sequences
    max-model-len: 32768            # prompt + output budget
    gpu-memory-utilization: 0.85    # fraction of GPU memory vLLM can use

